---
- hosts: container_registry
  gather_facts: yes
  become: yes
  roles:
    - container_registry

- hosts: control_planes,nodes
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/install_deps
