---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - install_ssl_deps

- hosts: ca_server
  gather_facts: yes
  become: yes
  roles:
    - create_ca

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - generate_ssl

- hosts: container_registry
  gather_facts: yes
  become: yes
  roles:
    - docker
    - container_registry

- hosts: load_balancer
  gather_facts: yes
  become: yes
  roles:
    - haproxy

- hosts: control_planes,nodes
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/install_deps
    - kubernetes/preconfig_nodes

- hosts: control_planes
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/pull_images

- hosts: control_planes[0]
  gather_facts: yes
  become: yes
  roles:
    - kubernetes/add_external_ca
