---
- name: Install dependencies
  include_tasks: install_deps.yml

- name: Create CA
  include_tasks: create_CA.yml

- name: Create private key for new certificate on ssl_server
  community.crypto.openssl_privatekey:
    path: "{{certs_dir}}/certificate.key"
  run_once: true

- name: Create certificate signing request (CSR) for new certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{certs_dir}}/certificate.key"
    subject_alt_name:
      - "DNS:*"
      - "IP:0.0.0.0"
  run_once: true
  register: csr

- name: Sign certificate with our CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{certs_dir}}/ca-certificate.crt"
    ownca_privatekey_path: "{{certs_dir}}/ca-certificate.key"
    ownca_privatekey_passphrase: "{{ secret_ca_passphrase }}"
    ownca_not_after: +365d # valid for one year
    ownca_not_before: "-1d" # valid since yesterday
  run_once: true
  register: certificate

- name: Write certificate file
  copy:
    dest: "{{certs_dir}}/certificate.crt"
    content: "{{ certificate.certificate }}"
  run_once: true

- name: Add certificate to trust store
  ansible.builtin.copy:
    remote_src: yes
    src: "{{certs_dir}}/ca-certificate.crt"
    dest: /etc/pki/ca-trust/source/anchors/

- name: Update trust store
  ansible.builtin.command: update-ca-trust
