---
- name: Make SELinux permissive
  selinux:
    state: permissive
    policy: targeted

- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}/packages/"
    state: directory
    mode: 0755

- name: Copy rpm packages to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ tmp_dir }}/packages/"
  with_fileglob:
    - "*.rpm"

- name: Find all rpm files in the directory
  find:
    paths: "{{ tmp_dir }}/packages/"
    patterns: "*.rpm"
  register: rpm_files

- name: Setting rpm_list
  set_fact:
    rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

- name: installing the rpm files
  yum:
    name: "{{rpm_list}}"
    state: present
    disablerepo: "*"
    disable_gpg_check: true

- name: Enable and start cri-o service
  service:
    name: crio
    enabled: yes
    state: started

- name: Enable and start kubelet service
  service:
    name: kubelet
    enabled: yes
    state: started
