---
- name: Make SELinux permissive
  ansible.builtin.shell: setenforce 0

- name: Make SELinux permissive on reboot
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: "SELINUX=enforcing"
    replace: "SELINUX=permissive"
    backup: yes

- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}/kube-packages/"
    state: directory
    mode: 0755

- name: Copy rpm packages to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ tmp_dir }}/kube-packages/"
  with_fileglob:
    - "*.rpm"

- name: Find all rpm files in the directory
  find:
    paths: "{{ tmp_dir }}/kube-packages/"
    patterns: "*.rpm"
  register: rpm_files

- name: Setting rpm_list
  set_fact:
    rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

- name: installing the rpm files
  yum:
    name: "{{rpm_list}}"
    state: present
    disablerepo: "*"
    disable_gpg_check: true
